name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. قم بعمل Checkout للكود
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. تسجيل الدخول إلى Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. بناء الصورة
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/financialwebsite-backend:latest ./Backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/financialwebsite-frontend:latest ./Frontend

      # 4. رفع الصور إلى Docker Hub
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/financialwebsite-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/financialwebsite-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # تشغيله بعد انتهاء مرحلة البناء

    steps:
      - name: Deploy application
        run: |
          echo "Here you can add deployment steps, like restarting Docker containers"
